name: Deploy to Github Pages - Build Website
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      
      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: ./dist

  deploy:
    name: Deploy Website
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    permissions:
      contents: write

    steps:
      - name: Download build-files created in previous job
        uses: actions/download-artifact@v2
        with:
          name: build-files
          path: ./dist

      - name: Deploy website to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
